name: CI

on: [push, pull_request]

env:
  ARKOUDA_DEVELOPER: true # faster compilation, and enable checks
  CHPL_RT_OVERSUBSCRIBED: yes # limit contention on limited CI hardware

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for tabs
      run: |
        ! git --no-pager grep -n $'\t' -- '*.chpl'

  arkouda_tests_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [chapel, chapel-gasnet]
    container:
      image: chapel/${{matrix.image}}:1.20.0
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y libhdf5-dev libzmq3-dev python3-pip
        echo "\$(eval \$(call add-path,/usr/lib/x86_64-linux-gnu/hdf5/serial/))" > Makefile.paths
    - name: Build/Install Arkouda
      run: |
        make
        pip3 install -e .
    - name: Arkouda make check
      run: |
        make check
    - name: Arkouda unit tests
      run: |
        ./util/test/runClient tests/operator_tests.py tests/string_test.py
    - name: Arkouda benchmark --correctness-only
      run: |
         ./benchmarks/run_benchmarks.py --correctness-only --dtype=int64
         ./benchmarks/run_benchmarks.py --correctness-only --dtype=float64
         ./benchmarks/run_benchmarks.py --correctness-only --dtype=bool scatter gather

  unit_tests_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [chapel, chapel-gasnet]
    container:
      image: chapel/${{matrix.image}}:1.20.0
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y libhdf5-dev libzmq3-dev python3-pip
        echo "\$(eval \$(call add-path,/usr/lib/x86_64-linux-gnu/hdf5/serial/))" > Makefile.paths
    - name: Run unit tests
      run: |
        start_test test/UnitTestSipHash.chpl
