name: CI

on: [push, pull_request]

env:
  ARKOUDA_QUICK_COMPILE: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for tabs
      run: |
        ! git --no-pager grep -n $'\t' -- '*.chpl'

  arkouda_tests_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [chapel, chapel-gasnet-smp]
    container:
      image: chapel/${{matrix.image}}:1.22.0
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y libhdf5-dev hdf5-tools libzmq3-dev python3-pip
        echo "\$(eval \$(call add-path,/usr/lib/x86_64-linux-gnu/hdf5/serial/))" > Makefile.paths
    - name: Build/Install Arkouda
      run: |
        make
        python3 -m pip install -e .[test]
    - name: Arkouda make check
      run: |
        make check
    - name: Arkouda unit tests
      run: |
        make test-python
    - name: Arkouda benchmark --correctness-only
      run: |
         ./benchmarks/run_benchmarks.py --correctness-only
         ./benchmarks/run_benchmarks.py --size=100 --gen-graphs

  unit_tests_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [chapel, chapel-gasnet-smp]
    container:
      image: chapel/${{matrix.image}}:1.22.0
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y libhdf5-dev libzmq3-dev python3-pip hdf5-tools
        echo "\$(eval \$(call add-path,/usr/lib/x86_64-linux-gnu/hdf5/serial/))" > Makefile.paths
    - name: Run unit tests
      run: |
        start_test test
